### ISSUE TITLE
test example does fail with valid or invalid devices

### ISSUE THREAD

**Issue by vkuehn** [vemonitor/vedirect_m8#6]
**Describe the bug**
python examples/vedirectsim.py --port /${HOME}/vmodem0 --device bmv700
causes the error message
ValueError: Fatal error, unable to set device settings on bmv700.Valid devices are : (bmv702, 23, smartsolar_1.39)

python examples/vedirectsim.py --port /${HOME}/vmodem0 --device bmv702
causes the same error

**To Reproduce**
python examples/vedirectsim.py --port /${HOME}/vmodem0 --device bmv700

**Expected behavior**
as in the documentation

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
just started and followed the steps on pypi on a fresh vm

**Comment by mano8** [comment]
Hi, thanks for the report and sorry for the bug.
Updating the package to version 1.3.0.3 with `pip install vedirect_m8 --upgrade` should resolve the issue.
See [this Pull Request](https://github.com/vemonitor/vedirect_m8/pull/7) for more information.
